version: "3"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: on-failure
    command: redis-server --appendonly yes
    volumes:
      - ./data:/data
    networks:
      test:

networks:
  test:
