server:
  port: 9999
spring:
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 7
        max-idle: 7
        min-idle: 2
        max-wait: -1ms
      shutdown-timeout: 200ms


stream:
  key: stream-statements
  consumer-group-name: stream-statements-load-balancer-group
  consumer-name: stream-statements-load-balancer
  failure-list-key: failure-list-lb