stream:
  key: stream-statements

publish:
  rate: 1000

server:
  port: 3000

spring:
  redis:
    host: redis
    port: 6379
    lettuce:
      pool:
        max-active: 7
        max-idle: 7
        min-idle: 2
        max-wait: -1ms
      shutdown-timeout: 200ms